# Generated by Django 3.2.7 on 2021-09-30 15:16

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Animal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('deleted', models.DateTimeField(editable=False, null=True)),
                ('Name', models.CharField(max_length=64, unique=True)),
                ('Max_Daily', models.IntegerField(default=4)),
                ('Inactive_Date', models.DateField(blank=True, null=True)),
                ('Comments', models.TextField(blank=True, max_length=255)),
            ],
            options={
                'ordering': ['Animal_Type'],
            },
        ),
        migrations.CreateModel(
            name='Animal_Type',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('deleted', models.DateTimeField(editable=False, null=True)),
                ('animal_type', models.CharField(max_length=32, serialize=False, unique=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Encounter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('deleted', models.DateTimeField(editable=False, null=True)),
                ('encounter_date', models.DateTimeField()),
                ('handling_time', models.BigIntegerField(blank=True, null=True)),
                ('crate_time', models.BigIntegerField(blank=True, null=True)),
                ('holding_time', models.BigIntegerField(blank=True, null=True)),
                ('comments', models.TextField(blank=True, max_length=255, null=True)),
                ('animal', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='encounters.animal')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='animal',
            name='Animal_Type',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, to='encounters.animal_type'),
        ),
    ]
