# Generated by Django 3.2.7 on 2021-10-30 20:51

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('encounters', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='animal',
            name='Comments',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='animal',
            name='Name',
            field=models.CharField(max_length=64),
        ),
        migrations.AlterField(
            model_name='encounter',
            name='comments',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='encounter',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Handler'),
        ),
    ]
